{% set name = "guide_seq" %}
{% set version = "1.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 733c04ad671727aeb9559ada2eb464d5e270ab41fa572827fb5f281e4c303f40

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - biopython
    - bwa=0.7.17
    - htseq
    - matplotlib
    - numpy
    - pandas
    - pyfaidx
    - pygments
    - pysam
    - pyyaml
    - regex
    - scipy
    - setuptools
    - sqlite
    - statsmodels
    - svgwrite
    - yaml
    - zlib
    - htslib=1.9
    - samtools=1.9
    - bedtools

test:
  imports:
    - guideseq
    - umi

about:
  home: https://github.com/tsailabSJ/guideseq
  license: GNU General Public License v2 (GPLv2)
  license_family: GPL2
  license_file: ''
  summary: An easy to use bioinformatic pipeline for the GUIDE-seq assay.
  description: "guide-seq\n\n\n"
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
